fixes:
	- "moodle/admin/tool/cleanupcourses/::"
ignore:
    # artificial/Moodle API files
    - "tests/**/*"
    - "lang/**/*"
    - "db/**/*"
    - "db/.*"
    - "settings.php"
    - "version.php"
    - "step/**/lang"
    - "step/**/db"
    - "step/**/settings.php"
    - "step/**/version.php"
    - "trigger/**/db"
    - "trigger/**/lang"
    - "trigger/**/settings.php"
    - "trigger/**/version.php"

